In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("./dataset.csv")
df

,Unnamed: 0,track_id,artists,album_name,track_name,popularity,duration_ms,explicit,danceability,energy,...,loudness,mode,speechiness,acousticness,instrumentalness,liveness,valence,tempo,time_signature,track_genre
0,0,5SuOikwiRyPMVoIQDJUgSV,Gen Hoshino,Comedy,Comedy,73,230666,False,0.676,0.4610,...,-6.746,0,0.1430,0.0322,0.000001,0.3580,0.7150,87.917,4,acoustic
1,1,4qPNDBW1i3p13qLCt0Ki3A,Ben Woodward,Ghost (Acoustic),Ghost - Acoustic,55,149610,False,0.420,0.1660,...,-17.235,1,0.0763,0.9240,0.000006,0.1010,0.2670,77.489,4,acoustic
2,2,1iJBSr7s7jYXzM8EGcbK5b,Ingrid Michaelson;ZAYN,To Begin Again,To Begin Again,57,210826,False,0.438,0.3590,...,-9.734,1,0.0557,0.2100,0.000000,0.1170,0.1200,76.332,4,acoustic
3,3,6lfxq3CG4xtTiEg7opyCyx,Kina Grannis,Crazy Rich Asians (Original Motion Picture Sou...,Can't Help Falling In Love,71,201933,False,0.266,0.0596,...,-18.515,1,0.0363,0.9050,0.000071,0.1320,0.1430,181.740,3,acoustic
4,4,5vjLSffimiIP26QG5WcN2K,Chord Overstreet,Hold On,Hold On,82,198853,False,0.618,0.4430,...,-9.681,1,0.0526,0.4690,0.000000,0.0829,0.1670,119.949,4,acoustic
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
113995,113995,2C3TZjDRiAzdyViavDJ217,Rainy Lullaby,#mindfulness - Soft Rain for Mindful Meditatio...,Sleep My Little Boy,21,384999,False,0.172,0.2350,...,-16.393,1,0.0422,0.6400,0.928000,0.0863,0.0339,125.995,5,world-music
113996,113996,1hIz5L4IB9hN3WRYPOCGPw,Rainy Lullaby,#mindfulness - Soft Rain for Mindful Meditatio...,Water Into Light,22,385000,False,0.174,0.1170,...,-18.318,0,0.0401,0.9940,0.976000,0.1050,0.0350,85.239,4,world-music
113997,113997,6x8ZfSoqDjuNa5SVP5QjvX,Cesária Evora,Best Of,Miss Perfumado,22,271466,False,0.629,0.3290,...,-10.895,0,0.0420,0.8670,0.000000,0.0839,0.7430,132.378,4,world-music
113998,113998,2e6sXL2bYv4bSz6VTdnfLs,Michael W. Smith,Change Your World,Friends,41,283893,False,0.587,0.5060,...,-10.889,1,0.0297,0.3810,0.000000,0.2700,0.4130,135.960,4,world-music
113999,113999,2hETkH7cOfqmz3LqZDHZf5,Cesária Evora,Miss Perfumado,Barbincor,22,241826,False,0.526,0.4870,...,-10.204,0,0.0725,0.6810,0.000000,0.0893,0.7080,79.198,4,world-music

In [3]:
def print_unique_values(df: pd.DataFrame, max_values: int=20):

    for col in df.columns:
        unique_vals = df[col].dropna().unique()
        n_unique = len(unique_vals)
        
        print(f"\nColumn: {col}")
        print(f"Number of unique values: {n_unique}")
        
        if n_unique <= max_values:
            print("Unique values:", unique_vals)
        else:
            print(f"First {max_values} unique values:", unique_vals[:max_values])
            print("... (truncated)")

In [4]:
print_unique_values(df)

Column: Unnamed: 0
Number of unique values: 114000
First 20 unique values: [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
... (truncated)

Column: track_id
Number of unique values: 89741
First 20 unique values: ['5SuOikwiRyPMVoIQDJUgSV' '4qPNDBW1i3p13qLCt0Ki3A'
 '1iJBSr7s7jYXzM8EGcbK5b' '6lfxq3CG4xtTiEg7opyCyx'
 '5vjLSffimiIP26QG5WcN2K' '01MVOl9KtVTNfFiBU9I7dc'
 '6Vc5wAMmXdKIAM7WUoEb7N' '1EzrEOXmMH3G43AXT1y7pA'
 '0IktbUcnAGrvD03AWnz3Q8' '7k9GuJYLp2AzqokyEdwEw2'
 '4mzP5mHkRvGxdhdGdAH7EJ' '5ivF4eQBqJiVL5IAE9jRyl'
 '4ptDJbJl35d7gQfeNteBwp' '0X9MxHR1rTkEHDjp95F2OO'
 '4LbWtBkN82ZRhz9jqzgrb3' '1KHdq8NK9QxnGjdXb55NiG'
 '6xKeQgzfjixSUld14qUezm' '4Yo0igmcoNyat1secaH0OD'
 '2qLMf6TuEC3ruGJg4SMMN6' '6CgNoAbFJ4Q4Id4EjtbXlC']
... (truncated)

Column: artists
Number of unique values: 31437
First 20 unique values: ['Gen Hoshino' 'Ben Woodward' 'Ingrid Michaelson;ZAYN' 'Kina Grannis'
 'Chord Overstreet' 'Tyrone Wells' 'A Great Big World;Christina Aguilera'
 'Jason Mraz' 'Jason Mraz;Colbie Caillat' 'Ross Copperman' 'Zack Tabudlo'
 'Dan Berk' 'Anna Hamilton' 'Chord Overstreet;Deepend' 'Landon Pigg'
 'Andrew Foy;Renee Foy' 'Boyce Avenue;Bea Miller'
 'Boyce Avenue;Jennel Garcia' 'Brandi Carlile;Sam Smith' 'KT Tunstall']
... (truncated)

Column: album_name
Number of unique values: 46589
First 20 unique values: ['Comedy' 'Ghost (Acoustic)' 'To Begin Again'
 'Crazy Rich Asians (Original Motion Picture Soundtrack)' 'Hold On'
 'Days I Will Remember' 'Is There Anybody Out There?'
 'We Sing. We Dance. We Steal Things.' 'Hunger' 'Episode'
 'Love Is a Four Letter Word' 'Solo' 'Bad Liar' 'Hold On (Remix)'
 'The Boy Who Never' 'ily (i love you baby)' 'At My Worst'
 'Cover Sessions, Vol. 4' 'Cover Sessions, Vol. 3'
 'Is There Anybody Out There? - Track by Track Commentary']
... (truncated)

Column: track_name
Number of unique values: 73608
First 20 unique values: ['Comedy' 'Ghost - Acoustic' 'To Begin Again' "Can't Help Falling In Love"
 'Hold On' 'Days I Will Remember' 'Say Something' "I'm Yours" 'Lucky'
 'Hunger' 'Give Me Your Forever' "I Won't Give Up" 'Solo' 'Bad Liar'
 'Hold On - Remix' 'Falling in Love at a Coffee Shop'
 'ily (i love you baby)' 'At My Worst' 'Photograph' 'Demons']
... (truncated)

Column: popularity
Number of unique values: 101
First 20 unique values: [73 55 57 71 82 58 74 80 56 69 52 62 54 68 67 75 63 70  0  1]
... (truncated)

Column: duration_ms
Number of unique values: 50697
First 20 unique values: [230666 149610 210826 201933 198853 214240 229400 242946 189613 205594
 244800 240165 198712 248448 188133 244986 129750 169728 260186 174174]
... (truncated)

Column: explicit
Number of unique values: 2
Unique values: [False  True]

Column: danceability
Number of unique values: 1174
First 20 unique values: [0.676 0.42  0.438 0.266 0.618 0.688 0.407 0.703 0.625 0.442 0.627 0.483
 0.489 0.691 0.755 0.706 0.795 0.717 0.678 0.572]
... (truncated)

Column: energy
Number of unique values: 2083
First 20 unique values: [0.461  0.166  0.359  0.0596 0.443  0.481  0.147  0.444  0.414  0.632
 0.363  0.303  0.314  0.234  0.78   0.561  0.112  0.0841 0.32   0.351 ]
... (truncated)

Column: key
Number of unique values: 12
Unique values: [ 1  0  2  6 11  8  4  7  3 10  5  9]

Column: loudness
Number of unique values: 19480
First 20 unique values: [ -6.746 -17.235  -9.734 -18.515  -9.681  -8.807  -8.822  -9.331  -8.7
  -6.77   -8.127 -10.058  -9.245  -6.441  -6.084  -7.933 -18.098 -18.09
  -8.393  -8.654]
... (truncated)

Column: mode
Number of unique values: 2
Unique values: [0 1]

Column: speechiness
Number of unique values: 1489
First 20 unique values: [0.143  0.0763 0.0557 0.0363 0.0526 0.105  0.0355 0.0417 0.0369 0.0295
 0.0291 0.0429 0.0331 0.0285 0.0327 0.0274 0.0391 0.0461 0.0283 0.0266]
... (truncated)

Column: acousticness
Number of unique values: 5061
First 20 unique values: [0.0322 0.924  0.21   0.905  0.469  0.289  0.857  0.559  0.294  0.426
 0.279  0.694  0.749  0.777  0.124  0.2    0.827  0.742  0.83   0.747 ]
... (truncated)

Column: instrumentalness
Number of unique values: 5346
First 20 unique values: [1.01e-06 5.56e-06 0.00e+00 7.07e-05 2.89e-06 4.19e-03 2.83e-05 4.56e-05
 4.03e-06 1.17e-05 1.37e-05 2.25e-04 2.56e-05 1.58e-05 3.37e-06 1.81e-06
 1.83e-04 2.56e-03 3.44e-05 2.02e-02]
... (truncated)

Column: liveness
Number of unique values: 1722
First 20 unique values: [0.358  0.101  0.117  0.132  0.0829 0.189  0.0913 0.0973 0.151  0.0735
 0.0928 0.115  0.113  0.12   0.121  0.179  0.125  0.0853 0.107  0.355 ]
... (truncated)

Column: valence
Number of unique values: 1790
First 20 unique values: [0.715  0.267  0.12   0.143  0.167  0.666  0.0765 0.712  0.669  0.196
 0.301  0.139  0.607  0.209  0.387  0.238  0.414  0.609  0.322  0.569 ]
... (truncated)

Column: tempo
Number of unique values: 45653
First 20 unique values: [ 87.917  77.489  76.332 181.74  119.949  98.017 141.284 150.96  130.088
  78.899  99.905 133.406 124.234  87.103 120.004  83.457 110.154  91.803
 107.946  90.032]
... (truncated)

Column: time_signature
Number of unique values: 5
Unique values: [4 3 1 5 0]

Column: track_genre
Number of unique values: 114
First 20 unique values: ['acoustic' 'afrobeat' 'alt-rock' 'alternative' 'ambient' 'anime'
 'black-metal' 'bluegrass' 'blues' 'brazil' 'breakbeat' 'british'
 'cantopop' 'chicago-house' 'children' 'chill' 'classical' 'club' 'comedy'
 'country']
... (truncated)

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 114000 entries, 0 to 113999
Data columns (total 21 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   Unnamed: 0        114000 non-null  int64
 1   track_id          114000 non-null  object
 2   artists           113999 non-null  object
 3   album_name        113999 non-null  object
 4   track_name        113999 non-null  object
 5   popularity        114000 non-null  int64
 6   duration_ms       114000 non-null  int64
 7   explicit          114000 non-null  bool
 8   danceability      114000 non-null  float64
 9   energy            114000 non-null  float64
 10  key               114000 non-null  int64
 11  loudness          114000 non-null  float64
 12  mode              114000 non-null  int64
 13  speechiness       114000 non-null  float64
 14  acousticness      114000 non-null  float64
 15  instrumentalness  114000 non-null  float64
 16  liveness          114000 non-null  float64
 17  valence           114000 non-null  float64
 18  tempo             114000 non-null  float64
 19  time_signature    114000 non-null  int64
 20  track_genre       114000 non-null  object
dtypes: bool(1), float64(9), int64(6), object(5)
memory usage: 17.5+ MB

In [6]:
duplicates = df[df.duplicated(subset=["track_id"], keep=False)]
duplicates.sort_values("track_id").head(20)

,Unnamed: 0,track_id,artists,album_name,track_name,popularity,duration_ms,explicit,danceability,energy,...,loudness,mode,speechiness,acousticness,instrumentalness,liveness,valence,tempo,time_signature,track_genre
15028,15028,001APMDOl3qtx1526T11n1,Pink Sweat$;Kirby,New RnB,Better,0,176320,False,0.613,0.471,...,-6.644,0,0.1070,0.31600,0.000001,0.1170,0.406,143.064,4,chill
103211,103211,001APMDOl3qtx1526T11n1,Pink Sweat$;Kirby,New RnB,Better,0,176320,False,0.613,0.471,...,-6.644,0,0.1070,0.31600,0.000001,0.1170,0.406,143.064,4,soul
85578,85578,001YQlnDSduXd5LgBd66gT,Soda Stereo,Soda Stereo (Remastered),El Tiempo Es Dinero - Remasterizado 2007,38,177266,False,0.554,0.921,...,-4.589,1,0.0758,0.01940,0.088100,0.3290,0.700,183.571,1,punk-rock
100420,100420,001YQlnDSduXd5LgBd66gT,Soda Stereo,Soda Stereo (Remastered),El Tiempo Es Dinero - Remasterizado 2007,38,177266,False,0.554,0.921,...,-4.589,1,0.0758,0.01940,0.088100,0.3290,0.700,183.571,1,ska
91801,91801,003vvx7Niy0yvhvHt4a68B,The Killers,Hot Fuss,Mr. Brightside,86,222973,False,0.352,0.911,...,-5.230,1,0.0747,0.00121,0.000000,0.0995,0.236,148.033,4,rock
3257,3257,003vvx7Niy0yvhvHt4a68B,The Killers,Hot Fuss,Mr. Brightside,86,222973,False,0.352,0.911,...,-5.230,1,0.0747,0.00121,0.000000,0.0995,0.236,148.033,4,alternative
2106,2106,003vvx7Niy0yvhvHt4a68B,The Killers,Hot Fuss,Mr. Brightside,86,222973,False,0.352,0.911,...,-5.230,1,0.0747,0.00121,0.000000,0.0995,0.236,148.033,4,alt-rock
33178,33178,004h8smbIoAkUNDJvVKwkG,Ouse;Powfu,Loners Diary,Lovemark,58,219482,True,0.808,0.331,...,-13.457,1,0.0557,0.13100,0.000000,0.2250,0.337,140.035,4,emo
94239,94239,004h8smbIoAkUNDJvVKwkG,Ouse;Powfu,Loners Diary,Lovemark,58,219482,True,0.808,0.331,...,-13.457,1,0.0557,0.13100,0.000000,0.2250,0.337,140.035,4,sad
97533,97533,006rHBBNLJMpQs8fRC2GDe,Calcinha Preta;Gusttavo Lima,CP 25 Anos (Ao Vivo em Aracaju),Agora Estou Sofrendo - Ao Vivo,47,260510,False,0.605,0.678,...,-3.257,1,0.0311,0.64200,0.000000,0.1570,0.439,125.059,4,sertanejo
77391,77391,006rHBBNLJMpQs8fRC2GDe,Calcinha Preta;Gusttavo Lima,CP 25 Anos (Ao Vivo em Aracaju),Agora Estou Sofrendo - Ao Vivo,47,260510,False,0.605,0.678,...,-3.257,1,0.0311,0.64200,0.000000,0.1570,0.439,125.059,4,pagode
35138,35138,006rHBBNLJMpQs8fRC2GDe,Calcinha Preta;Gusttavo Lima,CP 25 Anos (Ao Vivo em Aracaju),Agora Estou Sofrendo - Ao Vivo,47,260510,False,0.605,0.678,...,-3.257,1,0.0311,0.64200,0.000000,0.1570,0.439,125.059,4,forro
112131,112131,006tmNZLXEXPqdb23wwSN1,İlhan İrem,Bezginin Gizli Mektupları,Yemyeşil Bir Deniz,44,358173,False,0.486,0.568,...,-9.199,0,0.0417,0.65200,0.000000,0.8340,0.650,127.184,4,turkish
64662,64662,006tmNZLXEXPqdb23wwSN1,İlhan İrem,Bezginin Gizli Mektupları,Yemyeşil Bir Deniz,44,358173,False,0.486,0.568,...,-9.199,0,0.0417,0.65200,0.000000,0.8340,0.650,127.184,4,jazz
62346,62346,006tmNZLXEXPqdb23wwSN1,İlhan İrem,Bezginin Gizli Mektupları,Yemyeşil Bir Deniz,44,358173,False,0.486,0.568,...,-9.199,0,0.0417,0.65200,0.000000,0.8340,0.650,127.184,4,j-pop
63142,63142,006tmNZLXEXPqdb23wwSN1,İlhan İrem,Bezginin Gizli Mektupları,Yemyeşil Bir Deniz,44,358173,False,0.486,0.568,...,-9.199,0,0.0417,0.65200,0.000000,0.8340,0.650,127.184,4,j-rock
64246,64246,00970cTs7LnxWt0d5Qk08m,Ella Fitzgerald,Weihnachtslieder 2022,Sleigh Ride,0,175986,False,0.593,0.287,...,-12.472,1,0.0469,0.76400,0.000000,0.1530,0.639,77.117,4,jazz
8095,8095,00970cTs7LnxWt0d5Qk08m,Ella Fitzgerald,Weihnachtslieder 2022,Sleigh Ride,0,175986,False,0.593,0.287,...,-12.472,1,0.0469,0.76400,0.000000,0.1530,0.639,77.117,4,blues
71588,71588,00B7SBwrjbycLMOgAmeIU8,Red Hot Chili Peppers,Return of the Dream Canteen,Reach Out,66,251588,False,0.663,0.710,...,-5.550,0,0.0599,0.00745,0.005590,0.1470,0.487,120.984,4,metal
2870,2870,00B7SBwrjbycLMOgAmeIU8,Red Hot Chili Peppers,Return of the Dream Canteen,Reach Out,66,251588,False,0.663,0.710,...,-5.550,0,0.0599,0.00745,0.005590,0.1470,0.487,120.984,4,alt-rock

In [7]:
df.groupby("track_id")["track_genre"].nunique().sort_values(ascending=False).head(20)

track_id
6S3JlDAGk3uu3NtZbPnuhS    9
2Ey6v4Sekh3Z0RUSISRosD    8
2kkvB3RNRzwjFdGhaUA0tz    8
5ftfVzSLIi5ZxYdNbRtf41    7
2aaClnypAakdAmLw74JXxB    7
6bzWr3EpSEolVwlbLk58il    7
08kTa3SL9sV6Iy8KLKtGql    7
36NwMJRaCy7x77xYGJiG2M    7
61202Zzk9rk4bPMZLh2gr6    7
2qgXrzJsry4KgYoJCpuaul    7
1Gqpa08T7eBAvPQj9O9L2Q    7
5ZsAhuQ24mWHiduaxJqnhW    7
4aqS25F3ywJ9TGnNkOqilC    7
2vU6bm5hVF2idVknGzqyPL    7
0RSGPiykniIg8m7JhiAVv7    7
4XYieGKSlJlHpzB3bl6WMP    7
5sqkarfxe7UejHTlCtHCLS    7
54zCdkbIALAnv8Ihi3XWlD    7
5BI1XqMJK91dsEq0Bfe0Ov    7
4GPQDyw9hC1DiZVh0ouDVL    7
Name: track_genre, dtype: int64

In [8]:
track_id = df.groupby("track_id").filter(lambda x: x["track_genre"].nunique() > 1)["track_id"].iloc[0]

df[df["track_id"] == track_id][["track_id", "track_name", "track_genre"]]

                      track_id track_name        track_genre
0       5SuOikwiRyPMVoIQDJUgSV     Comedy           acoustic
62102   5SuOikwiRyPMVoIQDJUgSV     Comedy              j-pop
99152   5SuOikwiRyPMVoIQDJUgSV     Comedy  singer-songwriter
102151  5SuOikwiRyPMVoIQDJUgSV     Comedy         songwriter

In [9]:
df = df.drop(columns=["Unnamed: 0"])
df = df.dropna()

df = df.astype({
    "popularity": "int",
    "duration_ms": "int",
    "explicit": "bool",
    "danceability": "float",
    "energy": "float",
    "loudness": "float",
    "mode": "int",
    "speechiness": "float",
    "acousticness": "float",
    "instrumentalness": "float",
    "liveness": "float",
    "valence": "float",
    "tempo": "float",
    "track_genre": "string"
})

In [10]:
def popularity_bucket(x):
    if x >= 80:
        return "high"
    elif x >= 50:
        return "medium"
    return "low"

df["popularity_bucket"] = df["popularity"].apply(popularity_bucket)

In [11]:
df["artists"] = df["artists"].str.split(";")
df["artist_count"] = df["artists"].apply(len)

df["artist"] = df["artists"]
df = df.explode("artist")

In [12]:
df

,track_id,artists,album_name,track_name,popularity,duration_ms,explicit,danceability,energy,key,...,acousticness,instrumentalness,liveness,valence,tempo,time_signature,track_genre,popularity_bucket,artist_count,artist
0,5SuOikwiRyPMVoIQDJUgSV,[Gen Hoshino],Comedy,Comedy,73,230666,False,0.676,0.4610,1,...,0.0322,0.000001,0.3580,0.7150,87.917,4,acoustic,medium,1,Gen Hoshino
1,4qPNDBW1i3p13qLCt0Ki3A,[Ben Woodward],Ghost (Acoustic),Ghost - Acoustic,55,149610,False,0.420,0.1660,1,...,0.9240,0.000006,0.1010,0.2670,77.489,4,acoustic,medium,1,Ben Woodward
2,1iJBSr7s7jYXzM8EGcbK5b,"[Ingrid Michaelson, ZAYN]",To Begin Again,To Begin Again,57,210826,False,0.438,0.3590,0,...,0.2100,0.000000,0.1170,0.1200,76.332,4,acoustic,medium,2,Ingrid Michaelson
2,1iJBSr7s7jYXzM8EGcbK5b,"[Ingrid Michaelson, ZAYN]",To Begin Again,To Begin Again,57,210826,False,0.438,0.3590,0,...,0.2100,0.000000,0.1170,0.1200,76.332,4,acoustic,medium,2,ZAYN
3,6lfxq3CG4xtTiEg7opyCyx,[Kina Grannis],Crazy Rich Asians (Original Motion Picture Sou...,Can't Help Falling In Love,71,201933,False,0.266,0.0596,0,...,0.9050,0.000071,0.1320,0.1430,181.740,3,acoustic,medium,1,Kina Grannis
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
113995,2C3TZjDRiAzdyViavDJ217,[Rainy Lullaby],#mindfulness - Soft Rain for Mindful Meditatio...,Sleep My Little Boy,21,384999,False,0.172,0.2350,5,...,0.6400,0.928000,0.0863,0.0339,125.995,5,world-music,low,1,Rainy Lullaby
113996,1hIz5L4IB9hN3WRYPOCGPw,[Rainy Lullaby],#mindfulness - Soft Rain for Mindful Meditatio...,Water Into Light,22,385000,False,0.174,0.1170,0,...,0.9940,0.976000,0.1050,0.0350,85.239,4,world-music,low,1,Rainy Lullaby
113997,6x8ZfSoqDjuNa5SVP5QjvX,[Cesária Evora],Best Of,Miss Perfumado,22,271466,False,0.629,0.3290,0,...,0.8670,0.000000,0.0839,0.7430,132.378,4,world-music,low,1,Cesária Evora
113998,2e6sXL2bYv4bSz6VTdnfLs,[Michael W. Smith],Change Your World,Friends,41,283893,False,0.587,0.5060,7,...,0.3810,0.000000,0.2700,0.4130,135.960,4,world-music,low,1,Michael W. Smith
113999,2hETkH7cOfqmz3LqZDHZf5,[Cesária Evora],Miss Perfumado,Barbincor,22,241826,False,0.526,0.4870,1,...,0.6810,0.000000,0.0893,0.7080,79.198,4,world-music,low,1,Cesária Evora

In [13]:
df.to_parquet("spotify_tracks_clean.parquet", index=False)

In [14]:
df.columns

Index(['track_id', 'artists', 'album_name', 'track_name', 'popularity',
       'duration_ms', 'explicit', 'danceability', 'energy', 'key', 'loudness',
       'mode', 'speechiness', 'acousticness', 'instrumentalness', 'liveness',
       'valence', 'tempo', 'time_signature', 'track_genre',
       'popularity_bucket', 'artist_count', 'artist'],
      dtype='object')